config/routes.rb
Rails.application.routes.draw do
  devise_for :user

  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#top'
  get "about" => "home#about"
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :img, ImgUploader
  belongs_to :user, optional: true
  validates :title, presence: true
  validates :content, presence: true
  validates :img, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
    redirect_to posts_path if user_signed_in?
  end

  def about
  end

  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @search = Post.ransack(params[:q])
    @posts = @search.result
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :img, :remove_img)
    end
end

app/controllers/users/registrations_controller.rb
class User::SessionsController < Devise::RegistrationsController
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to new_user_registration_path, alert: 'ゲストユーザーの変更・削除はできません。'
    end
  end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<div id="main-contents">

<div class="bg">
<h2 class="pb-3">モワメームとはフランスのことばで「自分自身」という意味のことばです。</h2>
<p class="font-size: xx-large;">こんにちは！</p>
<p>このサイトは、<b>みんなのポエム</b>を読んだり投稿したりするサイトです！</p>
<p>このサイトでは普段人には言えない気持ちや、</p>
<p>誰かに共感して欲しいことなど、様々な思いをポエムとして文字に残し、</p>
<p>その気持ちにあった画像を投稿してみんなで共有しようというサイトです。</p>

</div>

app/views/home/top.html.erb
<div class="example">
  <p class="font-size: xx-large;">ようこそモワメームへ！</p>
  <h6>まずは右上を押して登録から！</h6>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">せかいみんながポエマー.</span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-light bg-light fixed-top">
<div class="container">
  <%= link_to 'Home', root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 <div class="collapse navbar-collapse" id="navbarSupportedContent">
   <ul class="navbar-nav ml-auto">
     <%  if user_signed_in?  %>
       <li class="nav-item active">
         <%= link_to "ログアウト", destroy_user_session_path, class: "nav-link text-right", method: :delete %>
       </li>
     <% else %>
       <li class="nav-item active">
         <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-right" %>
       </li>
       <li class="nav-item active">
         <%= link_to "ログイン", new_user_session_path, class: "nav-link text-right" %>
       </li>
       <li class="nav-item active">
         <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, class: "nav-link text-right", method: :post %>
       </li>
       <li class="nav-item active">
         <%= link_to "モワメームとは", about_path, class: "nav-link text-right" %>
       </li>
     <% end %>
   </ul>
 </div>
 </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container pt-5 mt-5">
    <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="container">
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :title, '投稿タイトル' %>
    <%= form.text_field :title , class: "form-control" %>
    <small id="poster-tip" class="form-text text-muted">
            投稿タイトルを入力してください。
    </small>
  </div>

  <div class="field">
    <%= form.label :content, '投稿内容' %>
    <%= form.text_area :content, class: 'form-control', rows:10 %>
    <small id="title-tip" class="form-text text-muted">
            投稿内容を入力してください。
    </small>
  </div>

  <div class="field">
  <%= form.label :画像 %><br />
  <%= form.file_field :img, class: "image" %>
    <small id="title-tip" class="form-text text-muted">
            ポエムにあった画像を選んでください。
    </small>
  </div>

  <div class="actions">
    <%= form.submit '投稿', class: "btn-info btn-block" %>
    <small id="submit-tip" class="form-text text-muted text-center py-3">
        投稿する前に投稿内容を見直してください!
    </small>
  </div>
  <%= link_to '戻る', posts_path, class: "btn btn-primary btn-block" %>
<% end %>
</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1 class="pt-5">編集</h1>

<%= render 'form', post: @post %>

<%= link_to '画像', @post, class: "btn btn-link" %> |
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1 class="text-center pt-5">ポエム一覧</h1>
<div class="container">
  <div class="text-right">
　    <%= search_form_for @search do |f| %>
      <%= f.label :title_cont, "キーワードから探す" %>
      <%= f.search_field :title_or_content_cont %>
    　　<%= f.submit "検索", class: "btn btn-outline-success" %>
    <% end %>
  </div>
  <div class="text-left pb-3">
    <%= link_to '新規投稿', new_post_path, class: "btn btn-info" %>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th class="text-center">タイトル</th>
      <th>本文</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= truncate(post.title, length: 10) %></td>
        <td><%= truncate(post.content, length: 30) %></td>
        <td><%= link_to post do %>
          <i class="fas fa-camera-retro fa-3x pb-1 ml-3"></i>
                    <% end %></td>
        <td><%= link_to '編集', edit_post_path(post), class: "btn btn-secondary" %></td>
        <td><%= link_to '削除', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1 class="pt-5 mt-5">新規投稿</h1>
    <%= render 'form', post: @post %>
    
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container pt-5">
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<strong>image:</strong>
<p class="text-center pt-3">
  <%= image_tag @post.img.url, :size =>'auto' %>
</p>

<%= link_to '編集', edit_post_path(@post), class: "btn btn-secondary" %> |
<%= link_to '戻る', posts_path, class: "btn btn-primary" %>
</div>